### ISSUE TITLE
非常感谢，提个建议

### ISSUE THREAD

**Issue by jerry011235** [flyou/FreeSSClient#1]
希望换成[ssr](https://github.com/breakwa11/shadowsocks-rss)，[v4.6.1-win.7z download](https://github.com/shadowsocksr/shadowsocksr-csharp/releases)

**Comment by flyou** [comment]
我一直用的ss，ssr我先试下稳定性，稍后更新

**Comment by jerry011235** [comment]
谢谢。
另如果有多个自定义的需爬取的免费账号页面该怎么弄？
所以希望 在脚本命令行界面 做个 能让用户输入 待爬取的多个自定义url 。
或者干脆做个gui，在关于界面把你的名号写上😁

**Comment by flyou** [comment]
@jerry011235 不同页面的爬去规则不一样，用户输入url也是不能识别的，关于gui界面可以考虑，多个途径获取ss账号正在做
